name: Push Docker Image

on:
  release:
    types:
      - published

jobs:
  push-docker-image:
    uses: Juansecu/Red5-Docker/.github/workflows/push-docker-image.yml@fb85d45e96140d97f93f1b132762e267edc7e60a
    with:
      version: ${{ github.event.release.tag_name }}
    secrets:
      dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}
      dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerhub-repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
